name: Build and Deploy to Cloud Run
on:
    push:
        branches:
            - main
# Environment variables available to all jobs and steps in this workflow
env:
    RUN_REGION: us-central1
    SERVICE_NAME: nodejsgithubactions
jobs:
    setup-build-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            
            # Setup gcloud CLI
            - uses: google-github-actions/setup-gcloud@main
              with:
                  version: '275.0.0'
                  service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
                  service_account_key: ${{ secrets.SERVICE_NAME }}
            
            # Configure gcloud CLI
            - name: gcloud Set up
              run: |
                  gcloud config set project ${{ secrets.PROJECT_ID }}
             
             #Build docker image
            - name: Image
              run: |-
                docker build -t gcr.io/${{ secrets.PROJECT_ID }}/$SERVICE_NAME:$GITHUB_SHA .
                
            #Configure docker to use the gcloud command-line tool as a credential helper
            - run: |
                  gcloud auth configure-docker -q
              # Push image to Google Container Registry
            - name: Build
              run: |-
                  docker push gcr.io/u${{ secrets.PROJECT_ID }}/$SERVICE_NAME:$GITHUB_SHA
            - name: Deploy
              run: |
                  gcloud run deploy $SERVICE_NAME --region $RUN_REGION --image gcr.io/${{ secrets.PROJECT_ID }}/$SERVICE_NAME:$GITHUB_SHA --allow-unauthenticated --platform managed
